### PR TITLE
WP-NOW: update documentation adding quickstart section and updating GIF

### PR DESCRIPTION
**Pull request by sejas**
## What?

* Update wp-now Readme for better simplicity and highlighting `npx` usage.

## Why?

- It was a great suggestion from https://github.com/WordPress/playground-tools/issues/194

## Testing Instructions

Confirm the README looks good.

https://github.com/WordPress/playground-tools/blob/aac36a5676ba9d5da1d2d44ca1590337017c3ac8/packages/wp-now/README.md

wp-now-quickstart

### CODE REVIEW

**Review by katinthehatsite — APPROVED** [review]
The changes look good on my end.

**Comment by StevenDufresne** [comment]
Nice! 

Can we delay the last frame in the GIF for an extra 2 seconds where we show the server URL since it's the _aha_ moment and the handoff for our users?

**Comment by StevenDufresne** [comment]
Readme changes look great!

**Comment by adamziel** [comment]
Lovely!

**Comment by sejas** [comment]
> Can we delay the last frame in the GIF for an extra 2 seconds where we show the server URL since it's the aha moment and the handoff for our users?

@StevenDufresne, I merged it to quickly. I updated the GIF here: https://github.com/WordPress/playground-tools/pull/207

**Pull request merged**
