### PR TITLE
Playground block: Add dismissible tip for exiting the editor with the keyboard

### PR DESCRIPTION
**Pull request by brandonpayton**
## What?

This PR adds a dismissible tip at the top of the editor to help keyboard-centric users know how they can leave the editor once it is focused.

Related to #316 

## Why?

As @joedolson [said](https://github.com/WordPress/playground-tools/issues/316):
"Having a visible text explanation would significantly improve the accessibility of the code view for keyboard users."

## Testing Instructions

- Run `npx nx dev wordpress-playground-block`
- View a post that has the Playground block
- Note the notice at the top of the editor
- Click "Dismiss" to dismiss the notice
- Confirm the notice is hidden
- Refresh the page and confirm the notice is no longer shown

To repeat this, open the dev tools and delete the key "playground-block-dismiss-exit-editor-tip".

### CODE REVIEW

**Comment by brandonpayton** [comment]
@joedolson, what do you think of this? The notice is focusable and dismissible with Enter key or a click.

Screenshot 2024-07-29 at 7 11 13 PM

**Comment by brandonpayton** [comment]
I think this notice probably needs an ARIA role since it is just a div.

**Review by bgrgicak — APPROVED** [review]

**Comment by joedolson** [comment]
@brandonpayton I don't think there's any particularly need for an ARIA role on this; it's just page content. There should be a spoken announcement to confirm that the notice is dismissed, however.

**Comment by joedolson** [comment]
I see; the dismiss 'button' is actually just a div. Is there a reason you're not actually using a button?

**Comment by brandonpayton** [comment]
@joedolson You were right. I tried to simplify this and just used a button for the entire notice.

> There should be a spoken announcement to confirm that the notice is dismissed, however.

I started looking at this but could use some advice because nothing I've tried so far is leading to right result. (I am testing with macOS VoiceOver by default but plan to check in NVDA as well).

What would be the cleanest way to announce the notice is dismissed? Should this be doable with using `aria-live` and related attributes?

**Comment by joedolson** [comment]
I think that having the entire panel be a button has some benefits, in that it guarantees that a user won't miss the instructions. 

If the 'Dismiss' text looks like it's clickable, however, it will be disconcerting to keyboard users who will not be able to focus it - and there shouldn't be focusable controls nested inside another control element. So perhaps that should have a design that makes it clear that it's the entire component that's reactive.

Here's some docs on the `withSpokenMessages` component: https://developer.wordpress.org/block-editor/reference-guides/components/with-spoken-messages/

**Comment by brandonpayton** [comment]
Thank you for the link to "withSpokenMessages"! I didn't know about that.

I wonder if it would be better to just be direct with an additional "(Click to dismiss this notice.)" in the banner like:
Screenshot 2024-07-30 at 3 49 13 PM

**Comment by brandonpayton** [comment]
I'm currently struggling to get the notice to be spoken by VoiceOver. Sometimes it has worked after VoiceOver finishes reading the entire contents of the code editor, which is focused as the keyboard-related is being dismissed. I tried using `speak(message, "assertive")`, but so far, that doesn't seem to result in anything being spoken.

**Comment by brandonpayton** [comment]
@joedolson when the notice is dismissed, I am moving the focus to the code editor so the focus is not lost. Is it right to say we need this kind of focus management when removing an element that was previously focused? Changing focus to the editor seemed like a meaningful focus transition since the user is acknowledging how to exit the editor.

If focusing the editor on dismissal is the right course, what I am finding is that the focus change interferes with the spoken announcement. In my testing, if the focus change is made in response to dismissing the exit-editor notice, VoiceOver does not speak an assertive message. It will speak a polite message but only after reading what appears to be the entire content of the editor, making the message untimely.

Do you have any suggestions about how we could address this?

**Comment by brandonpayton** [comment]
In order to keep things moving, I am going to merge this PR as is and create a follow up issue to address the spoken dismissal notification.

**Comment by brandonpayton** [comment]
The follow-up issue for the spoken announcement is https://github.com/WordPress/playground-tools/issues/343.

**Pull request merged**
